tasks:
- init: ./mvnw -B dependency:go-offline package -DskipTests
  command: ./mvnw spring-boot:run
  name: Run PetClinic app

# exposed ports
ports:
- port: 8080
  onOpen: open-browser # because authentication redirection doesn't seem to work embedded

vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack

jetbrains:
  intellij:  
    plugins:
      - com.haulmont.jpab
    prebuilds:
      version: both
